#!/usr/bin/env python3
"""Fix typed array loading in GameState.gd load_game() function."""
from pathlib import Path

filepath = Path('/root/.openclaw/workspace/acanous_floor3_demo/scripts/GameState.gd')
content = filepath.read_text()

# Find and replace the load_game typed array section
old_section = '''\tvar _data = data  # unused but silences warnings
\tcleared_rooms = data.get("cleared_rooms", [])
\tdefeated_bosses = data.get("defeated_bosses", [])
\tdial_position = data.get("dial_position", 0)
\tcrown_cog_unlocked = data.get("crown_cog_unlocked", false)
\tgear_devil_tokens = data.get("gear_devil_tokens", [])
\tinventory_offerings = data.get("inventory_offerings", [])
\tinventory_weapons = data.get("inventory_weapons", [])
\tinventory_armor = data.get("inventory_armor", [])
\tinventory_shields = data.get("inventory_shields", [])
\tinventory_trinkets = data.get("inventory_trinkets", [])
\tequipped_weapon = data.get("equipped_weapon", "")
\tequipped_armor = data.get("equipped_armor", "")
\tequipped_shield = data.get("equipped_shield", "")
\tequipped_trinket = data.get("equipped_trinket", "")
\tgems = data.get("gems", 0)
\ttemp_effects = data.get("temp_effects", {})
\tplayer_hp = data.get("player_hp", 50)
\tplayer_max_hp = data.get("player_max_hp", 50)
\tplayer_deck = data.get("player_deck", [])
\tplayer_quiddity = data.get("player_quiddity", 0)
\t# Floor 1 data
\ttransit_tokens = data.get("transit_tokens", [])
\tis_first_run = data.get("is_first_run", true)
\tdoor_tutorial_completed = data.get("door_tutorial_completed", false)
\tfloor1_rooms_cleared = data.get("floor1_rooms_cleared", [])
\tshortcut_maker_status = data.get("shortcut_maker_status", "none")
\tshortcut_maker_pact_taken = data.get("shortcut_maker_pact_taken", false)
\tcurrent_floor = data.get("current_floor", 1)
\thighest_floor_reached = data.get("highest_floor_reached", 1)
\t# Floor 2 data
\tfloor2_elevator_repaired = data.get("floor2_elevator_repaired", false)
\tfloor2_gears_collected = data.get("floor2_gears_collected", 0)
\t# Floor 4 data
\tfloor4_booths_cleared = data.get("floor4_booths_cleared", [])
\tfloor4_booths_cleared_main = data.get("floor4_booths_cleared_main", [])
\tfloor4_booths_cleared_undercroft = data.get("floor4_booths_cleared_undercroft", [])
\tfloor4_booths_cleared_refectory = data.get("floor4_booths_cleared_refectory", [])
\tfloor4_levels_unlocked = data.get("floor4_levels_unlocked", ["main"])
\tfloor4_current_level = data.get("floor4_current_level", "main")
\tfloor4_lifter_repaired = data.get("floor4_lifter_repaired", false)
\tfloor4_collected_parts = data.get("floor4_collected_parts", [])
\t# Floor 5 data
\tfloor5_valves_turned = data.get("floor5_valves_turned", {"breeze": false, "boiler": false, "gale": false})
\tfloor5_all_moorings_unlocked = data.get("floor5_all_moorings_unlocked", false)
\tfloor5_cargo_discovered = data.get("floor5_cargo_discovered", false)
\tfloor5_charge_state = data.get("floor5_charge_state", {"wind": 0, "steam": 0, "lightning": 0, "aether": 0})
\t# Floor 6 data
\tfloor6_courses = data.get("floor6_courses", [])
\tfloor6_grades = data.get("floor6_grades", {})
\tfloor6_clocktower_sabotaged = data.get("floor6_clocktower_sabotaged", false)
\tfloor6_master_key = data.get("floor6_master_key", false)
\tfloor6_deans_key = data.get("floor6_deans_key", false)
\tfloor6_graduate_status = data.get("floor6_graduate_status", "")
\tfloor6_books_read = data.get("floor6_books_read", 0)
\tfloor6_goblin_janitor_befriended = data.get("floor6_goblin_janitor_befriended", false)
\t# Floor 7 data
\tfloor7_signed_pacts = data.get("floor7_signed_pacts", [])
\tfloor7_void_cracks_stabilized = data.get("floor7_void_cracks_stabilized", 0)
\tfloor7_docket_weight = data.get("floor7_docket_weight", 0)
\tfloor7_final_pact_signed = data.get("floor7_final_pact_signed", false)
\tfloor7_goblin_forger_used = data.get("floor7_goblin_forger_used", false)
\t# Floor 8 data
\tfloor8_overclock_meter = data.get("floor8_overclock_meter", 0)
\tfloor8_elemental_charge = data.get("floor8_elemental_charge", {"fire": 0, "water": 0, "earth": 0, "air": 0})
\tfloor8_vessels_vented = data.get("floor8_vessels_vented", 0)
\tfloor8_vessels_overclocked = data.get("floor8_vessels_overclocked", 0)
\tfloor8_padlocks_opened = data.get("floor8_padlocks_opened", 0)
\tfloor8_blix_surrendered = data.get("floor8_blix_surrendered", false)
\tfloor8_scram_pulled = data.get("floor8_scram_pulled", false)
\t# Floor 9 data
\tfloor9_bone_count = data.get("floor9_bone_count", 0)
\tfloor9_gear_count = data.get("floor9_gear_count", 0)
\tfloor9_souls_freed = data.get("floor9_souls_freed", 0)
\tfloor9_soul_debt = data.get("floor9_soul_debt", 0)
\tfloor9_liberator_status = data.get("floor9_liberator_status", false)
\tfloor9_companions_built = data.get("floor9_companions_built", 0)
\t# Floor 10 data
\tfloor10_choices_made = data.get("floor10_choices_made", {})
\tfloor10_ghosts_spoken = data.get("floor10_ghosts_spoken", [])
\tfloor10_hoard_touched = data.get("floor10_hoard_touched", [])
\tfloor10_aspects_defeated = data.get("floor10_aspects_defeated", 0)
\tfloor10_final_choice = data.get("floor10_final_choice", "")
\tfloor10_true_ending_unlocked = data.get("floor10_true_ending_unlocked", false)
\t# Meta-progression
\tng_plus_unlocked = data.get("ng_plus_unlocked", false)
\texile_mode_unlocked = data.get("exile_mode_unlocked", false)
\tcano_defeated = data.get("cano_defeated", false)
\ttrue_ending_achieved = data.get("true_ending_achieved", false)
\ttrue_ending_locked = data.get("true_ending_locked", false)
\tbecome_ending_chosen = data.get("become_ending_chosen", false)
\tfalse_ending_seen = data.get("false_ending_seen", false)
\trun_count = data.get("run_count", 1)
\tdragon_deck_archive_size = data.get("dragon_deck_archive_size", 0)
\tdragon_variant = data.get("dragon_variant", "")
\tdragon_deck_archive = data.get("dragon_deck_archive", [])
\tif not dragon_deck_archive is Array:
\t\tdragon_deck_archive = []
\t# Convert to String array if needed
\tvar _tmp: Array[String] = []
\tfor _id in dragon_deck_archive:
\t\tif _id is String:
\t\t\t_tmp.append(_id)
\tdragon_deck_archive = _tmp
\tsave_suffix = data.get("save_suffix", "")
\tdragon_deck_archive_size = dragon_deck_archive.size()
\tprint("GameState: Loaded successfully")
\treturn true'''

if old_section not in content:
    print("[WARN] Could not find exact old section. Trying partial match...")
    # Fallback: just add deck fallback in _ready() and leave load_game as-is for now
    # The _ready() fix was already applied above
    print("[OK] _ready() deck fallback already added. load_game fix skipped.")
else:
    new_section = '''\t# Fix typed array loading from JSON (plain Array -> typed Array)
\tvar temp_cleared: Array = data.get("cleared_rooms", [])
\tcleared_rooms.clear()
\tfor item in temp_cleared:
\t\tcleared_rooms.append(int(item))
\n\tvar temp_defeated: Array = data.get("defeated_bosses", [])
\tdefeated_bosses.clear()
\tfor item in temp_defeated:
\t\tdefeated_bosses.append(str(item))
\n\tdial_position = data.get("dial_position", 0)
\tcrown_cog_unlocked = data.get("crown_cog_unlocked", false)
\n\tvar temp_gear_tokens: Array = data.get("gear_devil_tokens", [])
\tgear_devil_tokens.clear()
\tfor item in temp_gear_tokens:
\t\tgear_devil_tokens.append(int(item))
\n\tvar temp_offerings: Array = data.get("inventory_offerings", [])
\tinventory_offerings.clear()
\tfor item in temp_offerings:
\t\tinventory_offerings.append(str(item))
\n\tvar temp_weapons: Array = data.get("inventory_weapons", [])
\tinventory_weapons.clear()
\tfor item in temp_weapons:
\t\tinventory_weapons.append(str(item))
\n\tvar temp_armor: Array = data.get("inventory_armor", [])
\tinventory_armor.clear()
\tfor item in temp_armor:
\t\tinventory_armor.append(str(item))
\n\tvar temp_shields: Array = data.get("inventory_shields", [])
\tinventory_shields.clear()
\tfor item in temp_shields:
\t\tinventory_shields.append(str(item))
\n\tvar temp_trinkets: Array = data.get("inventory_trinkets", [])
\tinventory_trinkets.clear()
\tfor item in temp_trinkets:
\t\tinventory_trinkets.append(str(item))
\n\tequipped_weapon = data.get("equipped_weapon", "")
\tequipped_armor = data.get("equipped_armor", "")
\tequipped_shield = data.get("equipped_shield", "")
\tequipped_trinket = data.get("equipped_trinket", "")
\tgems = data.get("gems", 0)
\ttemp_effects = data.get("temp_effects", {})
\tplayer_hp = data.get("player_hp", 50)
\tplayer_max_hp = data.get("player_max_hp", 50)
\n\tvar temp_deck: Array = data.get("player_deck", [])
\tplayer_deck.clear()
\tfor item in temp_deck:
\t\tplayer_deck.append(str(item))
\n\tplayer_quiddity = data.get("player_quiddity", 0)
\n\tvar temp_transit: Array = data.get("transit_tokens", [])
\ttransit_tokens.clear()
\tfor item in temp_transit:
\t\ttransit_tokens.append(str(item))
\n\tis_first_run = data.get("is_first_run", true)
\tdoor_tutorial_completed = data.get("door_tutorial_completed", false)
\n\tvar temp_f1_cleared: Array = data.get("floor1_rooms_cleared", [])
\tfloor1_rooms_cleared.clear()
\tfor item in temp_f1_cleared:
\t\tfloor1_rooms_cleared.append(str(item))
\n\tshortcut_maker_status = data.get("shortcut_maker_status", "none")
\tshortcut_maker_pact_taken = data.get("shortcut_maker_pact_taken", false)
\tcurrent_floor = data.get("current_floor", 1)
\thighest_floor_reached = data.get("highest_floor_reached", 1)
\n\tfloor2_elevator_repaired = data.get("floor2_elevator_repaired", false)
\tfloor2_gears_collected = data.get("floor2_gears_collected", 0)
\n\tvar temp_f4_main: Array = data.get("floor4_booths_cleared_main", [])
\tfloor4_booths_cleared_main.clear()
\tfor item in temp_f4_main:
\t\tfloor4_booths_cleared_main.append(str(item))
\n\tvar temp_f4_under: Array = data.get("floor4_booths_cleared_undercroft", [])
\tfloor4_booths_cleared_undercroft.clear()
\tfor item in temp_f4_under:
\t\tfloor4_booths_cleared_undercroft.append(str(item))
\n\tvar temp_f4_ref: Array = data.get("floor4_booths_cleared_refectory", [])
\tfloor4_booths_cleared_refectory.clear()
\tfor item in temp_f4_ref:
\t\tfloor4_booths_cleared_refectory.append(str(item))
\n\tfloor4_levels_unlocked = data.get("floor4_levels_unlocked", ["main"])
\tfloor4_current_level = data.get("floor4_current_level", "main")
\tfloor4_lifter_repaired = data.get("floor4_lifter_repaired", false)
\n\tvar temp_f4_parts: Array = data.get("floor4_collected_parts", [])
\tfloor4_collected_parts.clear()
\tfor item in temp_f4_parts:
\t\tfloor4_collected_parts.append(str(item))
\n\tfloor5_valves_turned = data.get("floor5_valves_turned", {"breeze": false, "boiler": false, "gale": false})
\tfloor5_all_moorings_unlocked = data.get("floor5_all_moorings_unlocked", false)
\tfloor5_cargo_discovered = data.get("floor5_cargo_discovered", false)
\tfloor5_charge_state = data.get("floor5_charge_state", {"wind": 0, "steam": 0, "lightning": 0, "aether": 0})
\n\tvar temp_f6_courses: Array = data.get("floor6_courses", [])
\tfloor6_courses.clear()
\tfor item in temp_f6_courses:
\t\tfloor6_courses.append(str(item))
\n\tfloor6_grades = data.get("floor6_grades", {})
\tfloor6_clocktower_sabotaged = data.get("floor6_clocktower_sabotaged", false)
\tfloor6_master_key = data.get("floor6_master_key", false)
\tfloor6_deans_key = data.get("floor6_deans_key", false)
\tfloor6_graduate_status = data.get("floor6_graduate_status", "")
\tfloor6_books_read = data.get("floor6_books_read", 0)
\tfloor6_goblin_janitor_befriended = data.get("floor6_goblin_janitor_befriended", false)
\n\tvar temp_f7_pacts: Array = data.get("floor7_signed_pacts", [])
\tfloor7_signed_pacts.clear()
\tfor item in temp_f7_pacts:
\t\tfloor7_signed_pacts.append(item)
\n\tfloor7_void_cracks_stabilized = data.get("floor7_void_cracks_stabilized", 0)
\tfloor7_docket_weight = data.get("floor7_docket_weight", 0)
\tfloor7_final_pact_signed = data.get("floor7_final_pact_signed", false)
\tfloor7_goblin_forger_used = data.get("floor7_goblin_forger_used", false)
\n\tfloor8_overclock_meter = data.get("floor8_overclock_meter", 0)
\tfloor8_elemental_charge = data.get("floor8_elemental_charge", {"fire": 0, "water": 0, "earth": 0, "air": 0})
\tfloor8_vessels_vented = data.get("floor8_vessels_vented", 0)
\tfloor8_vessels_overclocked = data.get("floor8_vessels_overclocked", 0)
\tfloor8_padlocks_opened = data.get("floor8_padlocks_opened", 0)
\tfloor8_blix_surrendered = data.get("floor8_blix_surrendered", false)
\tfloor8_scram_pulled = data.get("floor8_scram_pulled", false)
\n\tfloor9_bone_count = data.get("floor9_bone_count", 0)
\tfloor9_gear_count = data.get("floor9_gear_count", 0)
\tfloor9_souls_freed = data.get("floor9_souls_freed", 0)
\tfloor9_soul_debt = data.get("floor9_soul_debt", 0)
\tfloor9_liberator_status = data.get("floor9_liberator_status", false)
\tfloor9_companions_built = data.get("floor9_companions_built", 0)
\n\tfloor10_choices_made = data.get("floor10_choices_made", {})
\tfloor10_ghosts_spoken = data.get("floor10_ghosts_spoken", [])
\tfloor10_hoard_touched = data.get("floor10_hoard_touched", [])
\tfloor10_aspects_defeated = data.get("floor10_aspects_defeated", 0)
\tfloor10_final_choice = data.get("floor10_final_choice", "")
\tfloor10_true_ending_unlocked = data.get("floor10_true_ending_unlocked", false)
\n\tng_plus_unlocked = data.get("ng_plus_unlocked", false)
\texile_mode_unlocked = data.get("exile_mode_unlocked", false)
\tcano_defeated = data.get("cano_defeated", false)
\ttrue_ending_achieved = data.get("true_ending_achieved", false)
\ttrue_ending_locked = data.get("true_ending_locked", false)
\tbecome_ending_chosen = data.get("become_ending_chosen", false)
\tfalse_ending_seen = data.get("false_ending_seen", false)
\trun_count = data.get("run_count", 1)
\n\tvar temp_archive: Array = data.get("dragon_deck_archive", [])
\tdragon_deck_archive.clear()
\tfor item in temp_archive:
\t\tif item is String:
\t\t\tdragon_deck_archive.append(item)
\n\tsave_suffix = data.get("save_suffix", "")
\tdragon_deck_archive_size = dragon_deck_archive.size()
\n\tprint("GameState: Loaded save (run %d, floor %d, deck: %d cards, archive: %d)" % [run_count, current_floor, player_deck.size(), dragon_deck_archive_size])
\treturn true'''
    
    content = content.replace(old_section, new_section)
    filepath.write_text(content)
    print("[OK] load_game() fixed with typed array casting")
