#!/usr/bin/env python3
"""
Wall Tile Placer — Floor 2: Places generated wall sprites along collision polygons.
Reads the CollisionPolygon2D nodes in each room scene and creates Sprite2D nodes
positioned and rotated to match each wall segment.

Usage:
    python3 place_f2_wall_tiles.py

Requires: Wall tiles in assets/sprites/floor2/walls/ (generated by generate_f2_wall_tileset.py)
"""

import math
import re
from pathlib import Path
from typing import List, Tuple, Optional

ROOMS = [
    "Floor2_Entry",
    "Floor2_Upper",
    "Floor2_Middle",
    "Floor2_Lower",
    "Floor2_Secret",
    "Floor2_SporeHeart",
]

SCENES_DIR = Path("scenes/rooms")
WALLS_DIR = Path("assets/sprites/floor2/walls")


def angle_to_cardinal(dx: float, dy: float) -> str:
    """Convert a direction vector to nearest cardinal/diagonal for tile selection."""
    angle = math.degrees(math.atan2(dy, dx))
    # Normalize to 0-360
    angle = (angle + 360) % 360
    
    # 8-way matching for tile selection
    if 337.5 <= angle or angle < 22.5:
        return "e"
    elif 22.5 <= angle < 67.5:
        return "se"
    elif 67.5 <= angle < 112.5:
        return "s"
    elif 112.5 <= angle < 157.5:
        return "sw"
    elif 157.5 <= angle < 202.5:
        return "w"
    elif 202.5 <= angle < 247.5:
        return "nw"
    elif 247.5 <= angle < 292.5:
        return "n"
    elif 292.5 <= angle < 337.5:
        return "ne"
    return "n"


def select_tile_for_segment(p1: Tuple[float, float], p2: Tuple[float, float], 
                             mid: Tuple[float, float], center: Tuple[float, float]) -> Optional[str]:
    """Select the best tile file for a wall segment based on its orientation and curvature."""
    dx = p2[0] - p1[0]
    dy = p2[1] - p1[1]
    
    # Direction of the wall (perpendicular to the normal from center)
    dir_card = angle_to_cardinal(dx, dy)
    
    # Check if segment is convex or concave relative to room center
    mid_to_center_x = center[0] - mid[0]
    mid_to_center_y = center[1] - mid[1]
    
    # Cross product to determine curvature
    cross = dx * mid_to_center_y - dy * mid_to_center_x
    is_convex = cross < 0  # Wall bulges outward
    
    # Map to tile filename
    tile_map = {
        # Straight segments - use the outward-facing direction
        "n": "wall_straight_s.png",   # Wall top edge (facing north, player sees south face)
        "s": "wall_straight_n.png",   # Wall bottom edge
        "e": "wall_straight_w.png",   # Wall right edge
        "w": "wall_straight_e.png",   # Wall left edge
        # Diagonals
        "nw": "wall_diag_nw_se.png",
        "se": "wall_diag_nw_se.png",
        "ne": "wall_diag_ne_sw.png",
        "sw": "wall_diag_ne_sw.png",
    }
    
    # For curved organic walls, try outer curve tiles
    if is_convex:
        curve_map = {
            "nw": "wall_outer_nw.png",
            "ne": "wall_outer_ne.png",
            "sw": "wall_outer_sw.png",
            "se": "wall_outer_se.png",
        }
        if dir_card in curve_map:
            return curve_map[dir_card]
    else:
        # Inner curve
        curve_map = {
            "nw": "wall_curve_nw.png",
            "ne": "wall_curve_ne.png",
            "sw": "wall_curve_sw.png",
            "se": "wall_curve_se.png",
        }
        if dir_card in curve_map:
            return curve_map[dir_card]
    
    return tile_map.get(dir_card)


def parse_polygon_points(line: str) -> List[Tuple[float, float]]:
    """Parse PackedVector2Array from a tscn line."""
    match = re.search(r'PackedVector2Array\((.*?)\)', line)
    if not match:
        return []
    
    nums = [float(x.strip()) for x in match.group(1).split(',')]
    return [(nums[i], nums[i+1]) for i in range(0, len(nums), 2)]


def compute_room_center(wall_points: List[List[Tuple[float, float]]]) -> Tuple[float, float]:
    """Compute approximate room center from all wall vertices."""
    all_x = []
    all_y = []
    for poly in wall_points:
        for p in poly:
            all_x.append(p[0])
            all_y.append(p[1])
    
    if not all_x:
        return (960, 800)
    
    return (sum(all_x) / len(all_x), sum(all_y) / len(all_y))


def generate_wall_sprites(room_name: str, filepath: Path) -> List[str]:
    """Generate Sprite2D node lines for wall tiles in a room scene."""
    lines = []
    
    # Read the scene file
    content = filepath.read_text()
    
    # Find all CollisionPolygon2D nodes and their polygons
    wall_polygons = []
    for match in re.finditer(r'\[node name="Wall_\d+" type="CollisionPolygon2D" parent="Walls"\]\npolygon = PackedVector2Array\((.*?)\)', content):
        points = parse_polygon_points(match.group(0))
        if points:
            wall_polygons.append(points)
    
    if not wall_polygons:
        print(f"  [WARN] {room_name}: No wall polygons found")
        return []
    
    center = compute_room_center(wall_polygons)
    
    sprite_idx = 0
    for poly in wall_polygons:
        # Each polygon is a quad: p1, p2, p3, p4
        # We only need p1-p2 (the inner edge facing the room)
        if len(poly) < 4:
            continue
        
        p1 = poly[0]
        p2 = poly[1]
        p3 = poly[2]
        p4 = poly[3]
        
        # Midpoint of the inner edge (p1-p2)
        mid = ((p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2)
        
        # Calculate rotation angle
        dx = p2[0] - p1[0]
        dy = p2[1] - p1[1]
        angle = math.degrees(math.atan2(dy, dx))
        
        # Select appropriate tile
        tile_file = select_tile_for_segment(p1, p2, mid, center)
        if not tile_file:
            tile_file = "wall_straight_n.png"  # fallback
        
        # Check if tile exists
        tile_path = WALLS_DIR / tile_file
        if not tile_path.exists():
            # Try alternate direction
            alt_file = tile_file.replace("straight_n", "straight_s").replace("straight_s", "straight_n")
            alt_file = alt_file.replace("straight_e", "straight_w").replace("straight_w", "straight_e")
            if not (WALLS_DIR / alt_file).exists():
                print(f"  [WARN] Tile not found: {tile_file}, skipping placement")
                continue
            tile_file = alt_file
        
        # Create Sprite2D node
        sprite_name = f"WallSprite_{sprite_idx:03d}"
        sprite_idx += 1
        
        lines.append(f'[node name="{sprite_name}" type="Sprite2D" parent="Walls"]')
        lines.append(f'position = Vector2({mid[0]:.1f}, {mid[1]:.1f})')
        lines.append(f'rotation = {math.radians(angle):.4f}')
        lines.append(f'texture = load("res://assets/sprites/floor2/walls/{tile_file}")')
        lines.append(f'z_index = 1')
        lines.append('')
    
    return lines


def add_ext_resources(content: str, needed_tiles: set) -> str:
    """Add ExtResource entries for wall tile textures."""
    
    # Find highest ext_resource id
    max_id = 0
    for match in re.finditer(r'\[ext_resource type="Texture2D".*?id="(\d+)_', content):
        max_id = max(max_id, int(match.group(1)))
    
    new_resources = []
    next_id = max_id + 1
    
    for tile_file in sorted(needed_tiles):
        tile_name = tile_file.replace(".png", "")
        # Check if already present
        if f'wall_{tile_name}"' in content:
            continue
        
        new_resources.append(
            f'[ext_resource type="Texture2D" path="res://assets/sprites/floor2/walls/{tile_file}" id="{next_id}_{tile_name}"]'
        )
        next_id += 1
    
    if new_resources:
        # Insert after last ext_resource line
        last_ext = content.rfind('[ext_resource')
        if last_ext != -1:
            last_ext_end = content.find('\n', last_ext) + 1
            content = content[:last_ext_end] + '\n'.join(new_resources) + '\n' + content[last_ext_end:]
    
    return content


def process_room(room_name: str):
    """Process a single room scene file."""
    filepath = SCENES_DIR / f"{room_name}.tscn"
    
    if not filepath.exists():
        print(f"  [SKIP] {room_name}.tscn not found")
        return
    
    print(f"\n[PROCESS] {room_name}")
    
    # Generate sprite nodes
    sprite_lines = generate_wall_sprites(room_name, filepath)
    
    if not sprite_lines:
        print(f"  [INFO] No wall sprites to place")
        return
    
    # Read current content
    content = filepath.read_text()
    
    # Remove any existing WallSprite nodes
    content = re.sub(r'\n\[node name="WallSprite_\d+".*?\n(?:.*?\n)*?\n', '\n', content)
    
    # Find where to insert (after the Walls node section)
    walls_section_end = content.find('\n[node name="Walls"')
    if walls_section_end == -1:
        walls_section_end = len(content)
    else:
        # Find the next top-level node after Walls
        next_node = re.search(r'\n\[node name="(?!Wall_)', content[walls_section_end+1:])
        if next_node:
            walls_section_end += next_node.start() + 1
        else:
            walls_section_end = len(content)
    
    # Insert sprite nodes
    content = content[:walls_section_end] + '\n' + '\n'.join(sprite_lines) + '\n' + content[walls_section_end:]
    
    # Insert sprite nodes
    content = content[:walls_section_end] + '\n' + '\n'.join(sprite_lines) + '\n' + content[walls_section_end:]
    
    # Write back
    filepath.write_text(content)
    print(f"  [OK] Placed {len(sprite_lines) // 6} wall sprites in {room_name}")


def main():
    print("=" * 60)
    print("Floor 2 Wall Tile Placer")
    print("=" * 60)
    print(f"Scenes:  {SCENES_DIR}")
    print(f"Tiles:   {WALLS_DIR}")
    print("=" * 60)
    
    if not WALLS_DIR.exists():
        print("\n[ERROR] Wall tiles not found! Run generate_f2_wall_tileset.py first.")
        return
    
    for room in ROOMS:
        process_room(room)
    
    print("\n" + "=" * 60)
    print("WALL TILE PLACEMENT COMPLETE")
    print("=" * 60)


if __name__ == "__main__":
    main()
